### ISSUE TITLE
Peer-to-Peer code review

### ISSUE THREAD

**Issue by JuanLPalacios** [richardoppiyo/To_do_list_webpack#5]
great going on your code!

## some highlights:

- your code is clear and well organized
- loved your elements module makes the code easier to read and more organized

here are some things you could improve:

- you should move changeStatus out of your todoList module as it is required on the next step of the project
- [OPTIONAL] you could add some comments to make  large sections easier to read through
- [OPTIONAL] you should take the screenshot out of the src/ folder as it is not part of your final build

**Comment by richardoppiyo** [comment]
Thank you and Noted. Updated
